### PR TITLE
Have Singlepass on non-arm64 and Cranelift on arm64

### PR DESCRIPTION
**Pull request by ddd-mtl**

### CODE REVIEW

**Comment by Connoropolous** [comment]
slick! can you expand on the background to this?

**Comment by ddd-mtl** [comment]
Holochain now uses wasmer 1.0 but Singlepass doesnt work anymore for aarch64 as noted in Wasmer's [Makefile](https://github.com/wasmerio/wasmer/blob/master/Makefile).
So this PR is for having holochain use Cranelift for aarch64 and Singlepass for all other archs.

At first I did this because Holochain was using Singlepass as default, so it was for having holochain work on aarch64.
Now holochain is using Cranelift as default so this is only useful if every you'd want Holochain to use Singlepass. Its stated thats its better suited for blockchain, so maybe its also better for holochain?

**Comment by thedavidmeister** [comment]
i'm not sure why it is better for blockchain, do you know @ddd-mtl ?

**Comment by ddd-mtl** [comment]
According to [this article](https://medium.com/wasmer/a-webassembly-compiler-tale-9ef37aa3b537):

```
When to use Single-pass:
 - Devices that need to run WebAssembly on the fly but can’t afford to run a “heavy” compiler: IoT devices
 - When we need to be cautious about JIT bombs (wasm modules that take a lot longer to compile than they would to execute): blockchain smart-contracts
 - Programs that need to start-up quickly, but don’t necessarily need extreme runtime performance: CLI tools, or development environments
 ```

I believe Holochain should benchmark the different compilers on decide for itself whats the better option. Hopefully the decision doesn't depend on the type of happ.

**Comment by thedavidmeister** [comment]
@ddd-mtl ah right, so i guess i'll hit these points to try and justify why we can get away with the single universal compiler:

- we don't run webassembly "on the fly" because we have a 3 level cache of serialized -> deserialized -> instantiated modules now https://github.com/holochain/holochain-wasmer/pull/68
- we don't need to be cautions about JIT bombs because unlike blockchain nobody is forced to run any particular wasm, a JIT bomb probably won't even get past installation
- we don't need to startup so quickly that compiling wasms will be such a problem, hitting the same module many times over a long period if time is a much bigger concern

not sure about other IoT concerns, but we are meaningfully different to blockchain here :)

**Pull request closed without merging**
