### PR TITLE
Show leak

### PR DESCRIPTION
**Pull request by freesig**
Shows a memory leak with cargo bench test_instances

### CODE REVIEW

**Comment by steveeJ** [comment]
@freesig I added the bench run to CI to demonstrate the failure I'm seeing locally with this branch:

```
Benchmarking wasm_instance/wasm_instance/test
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Link(Import("env", "__short_circuit", UnknownImport(Function(FunctionType { params: [I32, I32], results: [] }))))', benches/bench.rs:72:72
stack backtrace:
Benchmarking wasm_instance/wasm_instance/test: Warming up for 3.0000 s
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:1329:5
   3: criterion::Bencher<M>::iter
   4: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
   5: criterion::routine::Routine::sample
   6: criterion::analysis::common
   7: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
   8: bench::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Can you confirm this is the issue you want to highlight with the introduced bench case?

**Comment by syrusakbary** [comment]
I see that you are using Wasmer 2.0rc1 which should have the memory leak solved:
https://github.com/wasmerio/wasmer/tree/99f42b0c01ab04953bc5457d5708ac812d4bbddf

Adding @markmccaskey to the thread so he can help investigate if this on the Wasmer side

**Comment by freesig** [comment]
@steveeJ No this is not the error I'm trying to show. I'm not getting that error when I run these benchmarks. The benchmark runs without error but it eventually eats the systems memory.

**Comment by freesig** [comment]
@syrusakbary Thank you. Let me know if there's anything I can do to help.

**Comment by freesig** [comment]
We found this only happens when a new instance is create inside the loop. If the same `Instance` is cloned the leak doesn't build up but does happen a little.

**Comment by freesig** [comment]
This is the results of running the mem_test:
```
[
  Leaked {
        runs: 1000,
        num_threads: 1,
        bytes: 0,
        kb: 0,
        mb: 0,
    },
    Leaked {
        runs: 1,
        num_threads: 1,
        bytes: 48856,
        kb: 48,
        mb: 0,
    },
    Leaked {
        runs: 1,
        num_threads: 25,
        bytes: 395360,
        kb: 395,
        mb: 0,
    },
    Leaked {
        runs: 100,
        num_threads: 1,
        bytes: 671640,
        kb: 671,
        mb: 0,
    },
    Leaked {
        runs: 25,
        num_threads: 1,
        bytes: 804168,
        kb: 804,
        mb: 0,
    },
    Leaked {
        runs: 25,
        num_threads: 25,
        bytes: 2039776,
        kb: 2039,
        mb: 2,
    },
    Leaked {
        runs: 100,
        num_threads: 25,
        bytes: 10249192,
        kb: 10249,
        mb: 10,
    },
    Leaked {
        runs: 1000,
        num_threads: 25,
        bytes: 49320624,
        kb: 49320,
        mb: 49,
    },
]
```
Notice how the leak is much worse when threaded.
Oddly enough doing 1000 runs with a single thread doesn't result in a leak however doing 1 run with a single thread does.
But if we do 25 threads the leak is obvious and correlated with the number of runs.

**Comment by freesig** [comment]
Also just as a sanity check if you clone the instance instead of creating it from the module for each thread the leak does not happen.

**Pull request closed without merging**
